CREATE DATABASE IF NOT EXISTS library;

USE library;

CREATE TABLE IF NOT EXISTS author (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS book (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_author INT,
  id_category INT,
  title VARCHAR(100) NOT NULL,
  pages INT,
  CONSTRAINT fk_book_author
  FOREIGN KEY (id_author) REFERENCES author(id)
  ON DELETE SET NULL
  ON UPDATE CASCADE,
  CONSTRAINT fk_book_category
  FOREIGN KEY (id_category) REFERENCES category(id)
  ON DELETE SET NULL
  ON UPDATE CASCADE
);
